version: "3.7"
services:
  py3:
    build:
      context: ./py3
      dockerfile: Dockerfile
    restart: always
    environment:
        - SQL_HOSTNAME
        - SQL_USERNAME
        - SQL_PASSWORD
        - SQL_MAIN_DATABASE
        - SQL_PORT
        - SSH_HOST
        - SSH_USER
        - SSH_PASS
        - SSH_PORT
        - DIA_TABLE
        - SPY_TABLE
        - QQQ_TABLE
        - JSONFILENAME
        - DIA_SPREADSHEET_ID
        - DIA_SPREADSHEET_ID_NUM
        - SPY_SPREADSHEET_ID
        - SPY_SPREADSHEET_ID_NUM
        - QQQ_SPREADSHEET_ID
        - QQQ_SPREADSHEET_ID_NUM
    tty: true
    volumes:
      - ./py3/module:/app/py3/module